Repository anthonyargatoff/LifeCycle-Thugs, pull requests merged in 2024-04, with the labels that each got.

#142 fixed spacing issue on search page.
  flaskr/templates/Search.html
  flaskr/templates/footer.html
Labels: Task

#139 60 get data points onto frontend from flask
  flaskr/__init__.py
  flaskr/static/resources/scripts/dataScript.js
  flaskr/static/resources/scripts/mapScript.js
  flaskr/view.py
Labels: Feature

#141 140 create dynamic list of events
  flaskr/static/resources/scripts/mapScript.js
  flaskr/templates/Search.html
  flaskr/view.py
Labels: Feature

#146 Emails now have subject lines #122
  flaskr/notification/emailTest.py
  flaskr/notification/sendEmail.py
  flaskr/notifications/__init__.py
Labels: Feature

#149 Search panel update + notification / account management pages
  flaskr/auth.py
  flaskr/templates/Search.html
  flaskr/templates/accountManagement.html
  flaskr/templates/manageAccount.html
  flaskr/templates/manageNotifications.html
  flaskr/templates/navbar.html
Labels: Task

#153 60 get data points onto frontend from flask
  flaskr/static/resources/scripts/mapScript.js
  flaskr/templates/Search.html
  flaskr/view.py
Labels: Task

#151 134 add routing for signup and account management
  flaskr/__init__.py
  flaskr/auth.py
  flaskr/notifications_routes.py
  requirements.txt
  tests/test_app.py
Labels: Task

#159 Update requirements.txt
  requirements.txt
Labels: Chore

#167 week 11 scrum meeting
  scrum_meetings/SCRUM-MEETING-Week11.docx
Labels: Chore

#165 158 get data from api not local database
  flaskr/static/resources/scripts/mapScript.js
  flaskr/templates/Search.html
Labels: Feature

#166 163 javascript map implementation
  flaskr/static/resources/scripts/mapScript.js
  flaskr/templates/Search.html
  flaskr/view.py
Labels: Feature

#174 Predictions are now dynamically generated #164, companion to pr #166
  flaskr/distanceBetweenPoints/prediction.py
  flaskr/static/resources/scripts/mapScript.js
  flaskr/test/predictionTest.py
  flaskr/view.py
Labels: Feature

#180 Created the analytics page showing data of last 30 days
  flaskr/templates/Analytics.html
Labels: Task

#179 Notifications send automatically #155
  component_tests/notification_manager_test.py
  component_tests/notification_monitor_test.py
  component_tests/predictionTest.py
  component_tests/testdata/testSendNotify.db
  flaskr/__init__.py
  flaskr/databaseClasses/NotificationManager.py
  flaskr/notification/Job1.py
  flaskr/notification/NotificationMonitor.py
  requirements.txt
  testNotify.db
Labels: Feature

#192 Navbar updates by session login / logout
  database.db
  flaskr/auth.py
  flaskr/database.db
  flaskr/schema.sql
  flaskr/templates/logout.html
  flaskr/templates/manageNotifications.html
  flaskr/templates/navbar.html
  flaskr/templates/viewNotifications.html
Labels: Task

#198 Search Page: Update layout
  flaskr/templates/Search.html
Labels: Chore

#199 186 connect geocode api to create notifications
  flaskr/earthquakeAPI/geocode.py
  flaskr/notifications_routes.py
  flaskr/templates/manageNotifications.html
Labels: Feature

#210 Add search by location
  flaskr/templates/Search.html
Labels: Chore

#187 Clear guide for new user installation
  README.md
Labels: Chore

#200 fixed index in dbManager test for issue #201
  component_tests/db_manager_test.py
  component_tests/testdata/TestUser.db
Labels: Chore

#212 Geocode re integration
  flaskr/earthquakeAPI/geocode.py
  flaskr/notifications_routes.py
  flaskr/templates/manageNotifications.html
Labels: Feature

#214 admin manage users done
  flaskr/auth.py
  flaskr/databaseClasses/DBManager.py
  flaskr/templates/Admin.html
  flaskr/templates/adminViewUsers.html
  flaskr/templates/navbar.html
Labels: Task

#216 Add a try catch on sending notifications in case of poor data in lat/long from api
  flaskr/notification/NotificationMonitor.py
Labels: Chore
