Repository anthonyargatoff/LifeCycle-Thugs, pull requests merged in 2024-03, with the labels that each got.

#49 Scrum Meeting Week 7
  scrum_meetings/SCRUM-MEETING-Week7.docx
Labels: Chore

#50 Use case 5 admin view statistics
  milestones/milestone3/Use case sequence diagrams/Case5_Agmin_view_statistics.pdf
Labels: Task

#52 Move our M2 milestone to the M2 folder
  milestones/milestone2/Requirements Doc.pdf
Labels: Chore

#54 Created exploration folder, added bootstrap doc
  Exploration Documents/Bootstrap Exploration.pdf
Labels: Exploration

#53 SQLite Exploration
  SQLite/SQL_ForCreatingDB.txt
  SQLite/SQLiteNotes.txt
  SQLite/SQLiteTest.py
  SQLite/test.db
Labels: Exploration

#56 Diagram for Case3
  milestones/milestone3/Use case sequence diagrams/Case3_ Share.asta
  milestones/milestone3/Use case sequence diagrams/Case3_Share.pdf
Labels: Chore

#57 Basic HTML Pages
  HTML/Admin
  HTML/Landing
  HTML/Login
Labels: Task

#51 flask stuff for issue #45
  .gitignore
  README.md
  flaskr/__init__.py
  flaskr/__pycache__/__init__.cpython-310.pyc
  flaskr/__pycache__/__init__.cpython-311.pyc
  flaskr/static/resources/styles/mapStyles.css
  flaskr/templates/index.html
  flaskr/templates/login.html
  flaskr/templates/map.html
  requirements.txt
Labels: Task

#62 Week 8 scrum meeting added
  scrum_meetings/SCRUM-MEETING-Week8.docx
Labels: Chore

#65 removed __pycache__ folder
  .gitignore
  flaskr/__pycache__/__init__.cpython-310.pyc
  flaskr/__pycache__/__init__.cpython-311.pyc
  flaskr/templates/index.html
  flaskr/templates/login.html
  flaskr/templates/map.html
  flaskr/templates/signup.html
Labels: Chore

#63 added use case 7
  milestones/milestone3/Use case sequence diagrams/usecase7.drawio.pdf
Labels: Task

#67 Added and modified pages using Bootstrap
  HTML/About.html
  HTML/Admin.html
  HTML/Landing
  HTML/Landing.html
  HTML/Login
  HTML/Login.html
  HTML/Search.html
  HTML/Testing Screenshots/landingpage_desktop.png
  HTML/Testing Screenshots/landingpage_ipad.png
  HTML/Testing Screenshots/landingpage_mobile.png
  Images/Quake_Quest_Logo.png
Labels: Task

#68 Combined sequence diagram for M3 submission, #32
  milestones/milestone3/Use case sequence diagrams/View_Filter_Share.png
  milestones/milestone3/Use case sequence diagrams/Viewing and filtering and sharing.asta
  milestones/milestone3/Use case sequence diagrams/Viewing and filtering and sharing.asta.lock
Labels: Chore

#72 M3 diagrams, written, and combined, #41,#42
  milestones/milestone3/Diagrams.pdf
  milestones/milestone3/M3 Submission.pdf
  milestones/milestone3/M3_Submission_WithDiagrams.pdf
Labels: Chore

#73 issue 61
  .gitignore
  flaskr/__init__.py
  flaskr/static/resources/images/Quake_Quest_Logo.png
  flaskr/templates/About.html
  flaskr/templates/Admin.html
  flaskr/templates/Landing.html
  flaskr/templates/Search.html
  flaskr/templates/index.html
  flaskr/templates/login.html
  flaskr/templates/signup.html
Labels: Task

#69 58 database interaction classes
  API/EarthquakeApi.py
  API/test.py
  API/testdata/getParsedDataTest.txt
  API/testdata/multipleLinesTest.txt
  SQLite/SQLiteTest.py
  SQLite/db.sql
  SQLite/populateDatabase.py
  SQLite/quakeQuest.db
  SQLite/test.db
  test.db
Labels: Feature, Task

#83 added the map files
  HTML/About.html
  HTML/Admin.html
  HTML/Landing.html
  HTML/Login.html
  HTML/Search.html
  HTML/Testing Screenshots/landingpage_desktop.png
  HTML/Testing Screenshots/landingpage_ipad.png
  HTML/Testing Screenshots/landingpage_mobile.png
  Images/Quake_Quest_Logo.png
  flaskr/__init__.py
  flaskr/static/resources/scripts/dataScript.js
  flaskr/static/resources/scripts/mapScript.js
  flaskr/static/resources/styles/mapStyles.css
  flaskr/templates/Search.html
  flaskr/templates/index.html
  tests/conftest.py
Labels: Chore

#92 Add on delete and on update behaviour for the foreign key #81
  SQLite/databaseSchema.sql
Labels: Chore

#87 Fixing db user unittests #74
  SQLite/DBManagerTest.py
  SQLite/DBUser_tests_running.png
  SQLite/QuakeBase.db
  SQLite/Test.py
  SQLite/TestUser.d
  SQLite/TestUser.db
Labels: Chore

#91 Calculate distance between 2 coordinates issue #88
  src/distanceBetweenPoints/__init__.py
  src/distanceBetweenPoints/distanceBetweenPoints.py
  src/distanceBetweenPoints/readme.md
  src/test/distanceBetweenPointsTest.py
Labels: Task

#117 88 Notification class implementation
  Exploration Documents/310NotificationFlowChart.pdf
  flaskr/distanceBetweenPoints/__init__.py
  flaskr/distanceBetweenPoints/distanceBetweenPoints.py
  flaskr/distanceBetweenPoints/readme.md
  flaskr/notification/Notification.py
  flaskr/notification/__init__.py
  flaskr/test/distanceBetweenPointsTest.py
  flaskr/test/notificationTest.py
  tests/conftest.py
Labels: Feature

#119 Prediction exploration
  Exploration Documents/predictions.md
Labels: Exploration

#137 Setting up map element to search page
  flaskr/templates/Admin.html
  flaskr/templates/Search.html
  flaskr/templates/sampleEventList.html
Labels: Task

#131 added readme file to the tests package
  README.md
  flaskr/__init__.py
  flaskr/notification.py
  flaskr/notifications.py
  tests/README.md
  tests/test_app.py
Labels: Chore

#120 sendEmail can send emails given a body and an address #105
  flaskr/notifications/__init__.py
  flaskr/notifications/emailTest.py
  flaskr/notifications/sendEmail.py
Labels: Feature
